@startuml Base Log
Title Base Log

class Athlete {
name : string
password : string
email : string
instructors : [Athlete]
places : [Place]
age : number
gender : string
jumps : [Jump]

constructor(name : string, email : string, password : string, instructor : [], places : [])
}

class Jump {
' addJump(Jump)
' Verify: if that place exists
' Verify: if you are linked in date and place with a Jump
modality: BASE
athletes : [Athlete]
place: Place
date : Date
' this is a sinopse
description: string
diaryEntries: [DiaryEntry]

constructor (type : BASE, athletes : [], place : Place, date : Date)
}

class DiaryEntry {
  athlete: Athlete
  jump: Jump
  supporter: Supporter
  ' this is the full history text
  text: string
  attachments: [Image | Video | Audio]
}

class Place {
placeName : string
type : string
height : number
coordinates : [number, number]
landing : string
}

'non Athletes that supports the sport
class Supporter {
people: []
howSupports : string
}

' Head *- Hand : composition
' Parent o-- IndependentChild : agregation
' Need --> Use : association

Athlete --> Place : nedd a place to jump
Athlete -> Jump : Partial history

Place -> Jump : need info from Jump
Jump *-> DiaryEntry : Full history
Jump --> Supporter : non athletes that supports the sport
DiaryEntry --> Supporter : a history may not have supporters

@enduml



