@startuml Photo Liked

[*] -> PhotoWithoutLikes: Create a photo
PhotoWithoutLikes --> PhotoWithLikes : like
PhotoWithLikes --> PhotoWithLikes : like
PhotoWithLikes --> PhotoWithoutLikes : unlike

[*] -> DefaultPhotoLikedState: Create a photo
PhotoUnlikedState --> PhotoLikedState : liked
PhotoLikeState --> PhotoUnlikedState : unlike

@enduml
